const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('bf', {
  getSession: () => ipcRenderer.invoke('get-session'),
  getConfig: () => ipcRenderer.invoke('get-config'),
  sessionReady: (token) => ipcRenderer.send('session-ready', token),
  openLogin: () => ipcRenderer.send('open-login'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  logout: () => ipcRenderer.send('logout'),
  setInteractive: (v) => ipcRenderer.send('set-interactive', v),
  setOverlayBounds: (b) => ipcRenderer.send('set-overlay-bounds', b),
  captureScreen: () => ipcRenderer.invoke('capture-screen'),
  copyText: (t) => ipcRenderer.invoke('copy-text', t),
  onHotkey: (cb) => ipcRenderer.on('hotkey', (_e, action) => cb(action)),
  getHotkeys: () => ipcRenderer.invoke('get-hotkeys'),
  setHotkey: (action, key) => ipcRenderer.invoke('set-hotkey', action, key),
  resetHotkeys: () => ipcRenderer.invoke('reset-hotkeys'),
  onVoiceKey: (cb) => ipcRenderer.on('voice-key', (_e, data) => cb(data)),
  onUpdateReady: (cb) => ipcRenderer.on('update-ready', (_e, version) => cb(version)),
  onUpdateAvailable: (cb) => ipcRenderer.on('update-available', (_e, version) => cb(version)),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_e, percent) => cb(percent)),
  onUpdateError: (cb) => ipcRenderer.on('update-error', (_e, msg) => cb(msg)),
  onUpdateNone: (cb) => ipcRenderer.on('update-none', () => cb()),
  getVersion: () => ipcRenderer.invoke('get-version'),
  updateCheck: () => ipcRenderer.send('update-check'),
  updateDownload: () => ipcRenderer.send('update-download'),
  updateInstall: () => ipcRenderer.send('update-install'),
  onGameClosed: (cb) => ipcRenderer.on('game-closed', () => cb()),
  onGameFocus: (cb) => ipcRenderer.on('game-focus', (_e, focused) => cb(focused)),
});
